{% set name = "whatrecord" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 60dd887f45e282000b3f7b65b877677532bef237c35442b28dc3306b4292aee5

build:
  entry_points:
  - whatrecord = whatrecord.bin.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
  - python >=3.9
  - pip
  - setuptools >=45
  - setuptools_scm >=6.2
  run:
  - python >=3.9
  - aiohttp
  - apischema
  - epicsmacrolib
  - graphviz
  - jinja2
  - lark
  - python-graphviz <0.18
  - __unix  # [unix]
  - __win   # [win]
  - mslex >=0.3.0  # [win]

test:
  imports:
  - whatrecord
  commands:
  - pip check
  - whatrecord --help
  requires:
  - pip

about:
  home: https://github.com/pcdshub/whatrecord
  doc_url: https://pcdshub.github.io/whatrecord
  dev_url: https://github.com/pcdshub/whatrecord
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE.md
  summary: EPICS IOC meta information tool for indexing and searching

extra:
  recipe-maintainers:
    - tangkong
    - klauer
